/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gmt_gsoundsigdev_MainActivity */

#ifndef _Included_com_gmt_gsoundsigdev_MainActivity
#define _Included_com_gmt_gsoundsigdev_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gmt_gsoundsigdev_MainActivity
 * Method:    renderChirpData1
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_gmt_gsoundsigdev_MainActivity_renderChirpData1
  (JNIEnv *env, jobject instance ,jcharArray chararray);

/*
 * Class:     com_gmt_gsoundsigdev_MainActivity
 * Method:    renderChirpData2
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_gmt_gsoundsigdev_MainActivity_renderChirpData2
  (JNIEnv *env, jobject instance ,jcharArray chararray);

#ifdef __cplusplus
}
#endif
#endif
