/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shu_wyf_jnigsound_MainActivity */

#ifndef _Included_com_shu_wyf_jnigsound_MainActivity
#define _Included_com_shu_wyf_jnigsound_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shu_wyf_jnigsound_MainActivity
 * Method:    renderChirpData1
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_shu_wyf_jnigsound_MainActivity_renderChirpData1
  (JNIEnv *env, jobject instance , jcharArray chararray);

/*
 * Class:     com_shu_wyf_jnigsound_MainActivity
 * Method:    renderChirpData2
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_shu_wyf_jnigsound_MainActivity_renderChirpData2
  (JNIEnv *env, jobject instance , jcharArray chararray);

/*
 * Class:     com_shu_wyf_jnigsound_MainActivity
 * Method:    renderChirpData3
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_shu_wyf_jnigsound_MainActivity_renderChirpData3
  (JNIEnv *env, jobject instance , jcharArray chararray);

/*
 * Class:     com_shu_wyf_jnigsound_MainActivity
 * Method:    renderChirpData4
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_shu_wyf_jnigsound_MainActivity_renderChirpData4
  (JNIEnv *env, jobject instance , jcharArray chararray);

#ifdef __cplusplus
}
#endif
#endif
