/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shu_wyf_jnigsound_MainActivity */

#ifndef _Included_com_shu_wyf_jnigsound_MainActivity
#define _Included_com_shu_wyf_jnigsound_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shu_wyf_jnigsound_MainActivity
 * Method:    renderChirpData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shu_wyf_jnigsound_MainActivity_renderChirpData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
